#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbQuanLyNhaXe")]
	public partial class QuanLyDatVeXeLinQDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertChiTietVeXe(ChiTietVeXe instance);
    partial void UpdateChiTietVeXe(ChiTietVeXe instance);
    partial void DeleteChiTietVeXe(ChiTietVeXe instance);
    partial void InsertXe(Xe instance);
    partial void UpdateXe(Xe instance);
    partial void DeleteXe(Xe instance);
    partial void InsertDiaChiTrungChuyen(DiaChiTrungChuyen instance);
    partial void UpdateDiaChiTrungChuyen(DiaChiTrungChuyen instance);
    partial void DeleteDiaChiTrungChuyen(DiaChiTrungChuyen instance);
    partial void InsertIdentify(Identify instance);
    partial void UpdateIdentify(Identify instance);
    partial void DeleteIdentify(Identify instance);
    partial void InsertKhachHang(KhachHang instance);
    partial void UpdateKhachHang(KhachHang instance);
    partial void DeleteKhachHang(KhachHang instance);
    partial void InsertLichChay(LichChay instance);
    partial void UpdateLichChay(LichChay instance);
    partial void DeleteLichChay(LichChay instance);
    partial void InsertLichChay_Xe(LichChay_Xe instance);
    partial void UpdateLichChay_Xe(LichChay_Xe instance);
    partial void DeleteLichChay_Xe(LichChay_Xe instance);
    partial void InsertLoaiNhanVien(LoaiNhanVien instance);
    partial void UpdateLoaiNhanVien(LoaiNhanVien instance);
    partial void DeleteLoaiNhanVien(LoaiNhanVien instance);
    partial void InsertLoaiTaiKhoan(LoaiTaiKhoan instance);
    partial void UpdateLoaiTaiKhoan(LoaiTaiKhoan instance);
    partial void DeleteLoaiTaiKhoan(LoaiTaiKhoan instance);
    partial void InsertLoaiXe(LoaiXe instance);
    partial void UpdateLoaiXe(LoaiXe instance);
    partial void DeleteLoaiXe(LoaiXe instance);
    partial void InsertLoTrinh(LoTrinh instance);
    partial void UpdateLoTrinh(LoTrinh instance);
    partial void DeleteLoTrinh(LoTrinh instance);
    partial void InsertNhanVien(NhanVien instance);
    partial void UpdateNhanVien(NhanVien instance);
    partial void DeleteNhanVien(NhanVien instance);
    partial void InsertTaiKhoan(TaiKhoan instance);
    partial void UpdateTaiKhoan(TaiKhoan instance);
    partial void DeleteTaiKhoan(TaiKhoan instance);
    partial void InsertTrungChuyen(TrungChuyen instance);
    partial void UpdateTrungChuyen(TrungChuyen instance);
    partial void DeleteTrungChuyen(TrungChuyen instance);
    partial void InsertVeXe(VeXe instance);
    partial void UpdateVeXe(VeXe instance);
    partial void DeleteVeXe(VeXe instance);
    #endregion
		
		public QuanLyDatVeXeLinQDataContext() : 
				base(global::DTO.Properties.Settings.Default.dbQuanLyNhaXeConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyDatVeXeLinQDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyDatVeXeLinQDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyDatVeXeLinQDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyDatVeXeLinQDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ChiTietVeXe> ChiTietVeXes
		{
			get
			{
				return this.GetTable<ChiTietVeXe>();
			}
		}
		
		public System.Data.Linq.Table<Xe> Xes
		{
			get
			{
				return this.GetTable<Xe>();
			}
		}
		
		public System.Data.Linq.Table<DiaChiTrungChuyen> DiaChiTrungChuyens
		{
			get
			{
				return this.GetTable<DiaChiTrungChuyen>();
			}
		}
		
		public System.Data.Linq.Table<Identify> Identifies
		{
			get
			{
				return this.GetTable<Identify>();
			}
		}
		
		public System.Data.Linq.Table<KhachHang> KhachHangs
		{
			get
			{
				return this.GetTable<KhachHang>();
			}
		}
		
		public System.Data.Linq.Table<LichChay> LichChays
		{
			get
			{
				return this.GetTable<LichChay>();
			}
		}
		
		public System.Data.Linq.Table<LichChay_Xe> LichChay_Xes
		{
			get
			{
				return this.GetTable<LichChay_Xe>();
			}
		}
		
		public System.Data.Linq.Table<LoaiNhanVien> LoaiNhanViens
		{
			get
			{
				return this.GetTable<LoaiNhanVien>();
			}
		}
		
		public System.Data.Linq.Table<LoaiTaiKhoan> LoaiTaiKhoans
		{
			get
			{
				return this.GetTable<LoaiTaiKhoan>();
			}
		}
		
		public System.Data.Linq.Table<LoaiXe> LoaiXes
		{
			get
			{
				return this.GetTable<LoaiXe>();
			}
		}
		
		public System.Data.Linq.Table<LoTrinh> LoTrinhs
		{
			get
			{
				return this.GetTable<LoTrinh>();
			}
		}
		
		public System.Data.Linq.Table<NhanVien> NhanViens
		{
			get
			{
				return this.GetTable<NhanVien>();
			}
		}
		
		public System.Data.Linq.Table<TaiKhoan> TaiKhoans
		{
			get
			{
				return this.GetTable<TaiKhoan>();
			}
		}
		
		public System.Data.Linq.Table<TrungChuyen> TrungChuyens
		{
			get
			{
				return this.GetTable<TrungChuyen>();
			}
		}
		
		public System.Data.Linq.Table<VeXe> VeXes
		{
			get
			{
				return this.GetTable<VeXe>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietVeXe")]
	public partial class ChiTietVeXe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaVeXe;
		
		private string _GheNgoi;
		
		private EntityRef<VeXe> _VeXe;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaVeXeChanging(string value);
    partial void OnMaVeXeChanged();
    partial void OnGheNgoiChanging(string value);
    partial void OnGheNgoiChanged();
    #endregion
		
		public ChiTietVeXe()
		{
			this._VeXe = default(EntityRef<VeXe>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaVeXe", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaVeXe
		{
			get
			{
				return this._MaVeXe;
			}
			set
			{
				if ((this._MaVeXe != value))
				{
					if (this._VeXe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaVeXeChanging(value);
					this.SendPropertyChanging();
					this._MaVeXe = value;
					this.SendPropertyChanged("MaVeXe");
					this.OnMaVeXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GheNgoi", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string GheNgoi
		{
			get
			{
				return this._GheNgoi;
			}
			set
			{
				if ((this._GheNgoi != value))
				{
					this.OnGheNgoiChanging(value);
					this.SendPropertyChanging();
					this._GheNgoi = value;
					this.SendPropertyChanged("GheNgoi");
					this.OnGheNgoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VeXe_ChiTietVeXe", Storage="_VeXe", ThisKey="MaVeXe", OtherKey="MaVeXe", IsForeignKey=true)]
		public VeXe VeXe
		{
			get
			{
				return this._VeXe.Entity;
			}
			set
			{
				VeXe previousValue = this._VeXe.Entity;
				if (((previousValue != value) 
							|| (this._VeXe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._VeXe.Entity = null;
						previousValue.ChiTietVeXes.Remove(this);
					}
					this._VeXe.Entity = value;
					if ((value != null))
					{
						value.ChiTietVeXes.Add(this);
						this._MaVeXe = value.MaVeXe;
					}
					else
					{
						this._MaVeXe = default(string);
					}
					this.SendPropertyChanged("VeXe");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Xe")]
	public partial class Xe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaXe;
		
		private string _BienSo;
		
		private int _SoGhe;
		
		private int _MaLoaiXe;
		
		private int _fl_Xoa;
		
		private EntitySet<LichChay_Xe> _LichChay_Xes;
		
		private EntityRef<LoaiXe> _LoaiXe;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaXeChanging(string value);
    partial void OnMaXeChanged();
    partial void OnBienSoChanging(string value);
    partial void OnBienSoChanged();
    partial void OnSoGheChanging(int value);
    partial void OnSoGheChanged();
    partial void OnMaLoaiXeChanging(int value);
    partial void OnMaLoaiXeChanged();
    partial void Onfl_XoaChanging(int value);
    partial void Onfl_XoaChanged();
    #endregion
		
		public Xe()
		{
			this._LichChay_Xes = new EntitySet<LichChay_Xe>(new Action<LichChay_Xe>(this.attach_LichChay_Xes), new Action<LichChay_Xe>(this.detach_LichChay_Xes));
			this._LoaiXe = default(EntityRef<LoaiXe>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaXe", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaXe
		{
			get
			{
				return this._MaXe;
			}
			set
			{
				if ((this._MaXe != value))
				{
					this.OnMaXeChanging(value);
					this.SendPropertyChanging();
					this._MaXe = value;
					this.SendPropertyChanged("MaXe");
					this.OnMaXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BienSo", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string BienSo
		{
			get
			{
				return this._BienSo;
			}
			set
			{
				if ((this._BienSo != value))
				{
					this.OnBienSoChanging(value);
					this.SendPropertyChanging();
					this._BienSo = value;
					this.SendPropertyChanged("BienSo");
					this.OnBienSoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoGhe", DbType="Int NOT NULL")]
		public int SoGhe
		{
			get
			{
				return this._SoGhe;
			}
			set
			{
				if ((this._SoGhe != value))
				{
					this.OnSoGheChanging(value);
					this.SendPropertyChanging();
					this._SoGhe = value;
					this.SendPropertyChanged("SoGhe");
					this.OnSoGheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiXe", DbType="Int NOT NULL")]
		public int MaLoaiXe
		{
			get
			{
				return this._MaLoaiXe;
			}
			set
			{
				if ((this._MaLoaiXe != value))
				{
					if (this._LoaiXe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLoaiXeChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiXe = value;
					this.SendPropertyChanged("MaLoaiXe");
					this.OnMaLoaiXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fl_Xoa", DbType="Int NOT NULL")]
		public int fl_Xoa
		{
			get
			{
				return this._fl_Xoa;
			}
			set
			{
				if ((this._fl_Xoa != value))
				{
					this.Onfl_XoaChanging(value);
					this.SendPropertyChanging();
					this._fl_Xoa = value;
					this.SendPropertyChanged("fl_Xoa");
					this.Onfl_XoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Xe_LichChay_Xe", Storage="_LichChay_Xes", ThisKey="MaXe", OtherKey="MaXe")]
		public EntitySet<LichChay_Xe> LichChay_Xes
		{
			get
			{
				return this._LichChay_Xes;
			}
			set
			{
				this._LichChay_Xes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiXe_Xe", Storage="_LoaiXe", ThisKey="MaLoaiXe", OtherKey="MaLoaiXe", IsForeignKey=true)]
		public LoaiXe LoaiXe
		{
			get
			{
				return this._LoaiXe.Entity;
			}
			set
			{
				LoaiXe previousValue = this._LoaiXe.Entity;
				if (((previousValue != value) 
							|| (this._LoaiXe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiXe.Entity = null;
						previousValue.Xes.Remove(this);
					}
					this._LoaiXe.Entity = value;
					if ((value != null))
					{
						value.Xes.Add(this);
						this._MaLoaiXe = value.MaLoaiXe;
					}
					else
					{
						this._MaLoaiXe = default(int);
					}
					this.SendPropertyChanged("LoaiXe");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_LichChay_Xes(LichChay_Xe entity)
		{
			this.SendPropertyChanging();
			entity.Xe = this;
		}
		
		private void detach_LichChay_Xes(LichChay_Xe entity)
		{
			this.SendPropertyChanging();
			entity.Xe = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DiaChiTrungChuyen")]
	public partial class DiaChiTrungChuyen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDiaChiTrungChuyen;
		
		private string _DiaChi;
		
		private int _fl_Xoa;
		
		private EntitySet<TrungChuyen> _TrungChuyens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDiaChiTrungChuyenChanging(string value);
    partial void OnMaDiaChiTrungChuyenChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void Onfl_XoaChanging(int value);
    partial void Onfl_XoaChanged();
    #endregion
		
		public DiaChiTrungChuyen()
		{
			this._TrungChuyens = new EntitySet<TrungChuyen>(new Action<TrungChuyen>(this.attach_TrungChuyens), new Action<TrungChuyen>(this.detach_TrungChuyens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDiaChiTrungChuyen", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDiaChiTrungChuyen
		{
			get
			{
				return this._MaDiaChiTrungChuyen;
			}
			set
			{
				if ((this._MaDiaChiTrungChuyen != value))
				{
					this.OnMaDiaChiTrungChuyenChanging(value);
					this.SendPropertyChanging();
					this._MaDiaChiTrungChuyen = value;
					this.SendPropertyChanged("MaDiaChiTrungChuyen");
					this.OnMaDiaChiTrungChuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fl_Xoa", DbType="Int NOT NULL")]
		public int fl_Xoa
		{
			get
			{
				return this._fl_Xoa;
			}
			set
			{
				if ((this._fl_Xoa != value))
				{
					this.Onfl_XoaChanging(value);
					this.SendPropertyChanging();
					this._fl_Xoa = value;
					this.SendPropertyChanged("fl_Xoa");
					this.Onfl_XoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DiaChiTrungChuyen_TrungChuyen", Storage="_TrungChuyens", ThisKey="MaDiaChiTrungChuyen", OtherKey="MaDiaChiTrungChuyen")]
		public EntitySet<TrungChuyen> TrungChuyens
		{
			get
			{
				return this._TrungChuyens;
			}
			set
			{
				this._TrungChuyens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TrungChuyens(TrungChuyen entity)
		{
			this.SendPropertyChanging();
			entity.DiaChiTrungChuyen = this;
		}
		
		private void detach_TrungChuyens(TrungChuyen entity)
		{
			this.SendPropertyChanging();
			entity.DiaChiTrungChuyen = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Identify")]
	public partial class Identify : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _NhanVien;
		
		private System.Nullable<int> _KhachHang;
		
		private System.Nullable<int> _LoTrinh;
		
		private System.Nullable<int> _Xe;
		
		private System.Nullable<int> _LichChay;
		
		private System.Nullable<int> _VeXe;
		
		private System.Nullable<int> _LichChay_Xe;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNhanVienChanging(System.Nullable<int> value);
    partial void OnNhanVienChanged();
    partial void OnKhachHangChanging(System.Nullable<int> value);
    partial void OnKhachHangChanged();
    partial void OnLoTrinhChanging(System.Nullable<int> value);
    partial void OnLoTrinhChanged();
    partial void OnXeChanging(System.Nullable<int> value);
    partial void OnXeChanged();
    partial void OnLichChayChanging(System.Nullable<int> value);
    partial void OnLichChayChanged();
    partial void OnVeXeChanging(System.Nullable<int> value);
    partial void OnVeXeChanged();
    partial void OnLichChay_XeChanging(System.Nullable<int> value);
    partial void OnLichChay_XeChanged();
    #endregion
		
		public Identify()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NhanVien", DbType="Int")]
		public System.Nullable<int> NhanVien
		{
			get
			{
				return this._NhanVien;
			}
			set
			{
				if ((this._NhanVien != value))
				{
					this.OnNhanVienChanging(value);
					this.SendPropertyChanging();
					this._NhanVien = value;
					this.SendPropertyChanged("NhanVien");
					this.OnNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KhachHang", DbType="Int")]
		public System.Nullable<int> KhachHang
		{
			get
			{
				return this._KhachHang;
			}
			set
			{
				if ((this._KhachHang != value))
				{
					this.OnKhachHangChanging(value);
					this.SendPropertyChanging();
					this._KhachHang = value;
					this.SendPropertyChanged("KhachHang");
					this.OnKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoTrinh", DbType="Int")]
		public System.Nullable<int> LoTrinh
		{
			get
			{
				return this._LoTrinh;
			}
			set
			{
				if ((this._LoTrinh != value))
				{
					this.OnLoTrinhChanging(value);
					this.SendPropertyChanging();
					this._LoTrinh = value;
					this.SendPropertyChanged("LoTrinh");
					this.OnLoTrinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Xe", DbType="Int")]
		public System.Nullable<int> Xe
		{
			get
			{
				return this._Xe;
			}
			set
			{
				if ((this._Xe != value))
				{
					this.OnXeChanging(value);
					this.SendPropertyChanging();
					this._Xe = value;
					this.SendPropertyChanged("Xe");
					this.OnXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LichChay", DbType="Int")]
		public System.Nullable<int> LichChay
		{
			get
			{
				return this._LichChay;
			}
			set
			{
				if ((this._LichChay != value))
				{
					this.OnLichChayChanging(value);
					this.SendPropertyChanging();
					this._LichChay = value;
					this.SendPropertyChanged("LichChay");
					this.OnLichChayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VeXe", DbType="Int")]
		public System.Nullable<int> VeXe
		{
			get
			{
				return this._VeXe;
			}
			set
			{
				if ((this._VeXe != value))
				{
					this.OnVeXeChanging(value);
					this.SendPropertyChanging();
					this._VeXe = value;
					this.SendPropertyChanged("VeXe");
					this.OnVeXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LichChay_Xe", DbType="Int")]
		public System.Nullable<int> LichChay_Xe
		{
			get
			{
				return this._LichChay_Xe;
			}
			set
			{
				if ((this._LichChay_Xe != value))
				{
					this.OnLichChay_XeChanging(value);
					this.SendPropertyChanging();
					this._LichChay_Xe = value;
					this.SendPropertyChanged("LichChay_Xe");
					this.OnLichChay_XeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhachHang")]
	public partial class KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKhachHang;
		
		private string _TenKhachHang;
		
		private string _GioiTinh;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _DienThoai;
		
		private string _CCCD;
		
		private string _DiaChi;
		
		private string _TenDangNhap;
		
		private System.DateTime _fl_NgayThem;
		
		private System.Nullable<System.DateTime> _fl_NgaySua;
		
		private int _fl_Xoa;
		
		private EntitySet<VeXe> _VeXes;
		
		private EntityRef<TaiKhoan> _TaiKhoan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKhachHangChanging(string value);
    partial void OnMaKhachHangChanged();
    partial void OnTenKhachHangChanging(string value);
    partial void OnTenKhachHangChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnDienThoaiChanging(string value);
    partial void OnDienThoaiChanged();
    partial void OnCCCDChanging(string value);
    partial void OnCCCDChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnTenDangNhapChanging(string value);
    partial void OnTenDangNhapChanged();
    partial void Onfl_NgayThemChanging(System.DateTime value);
    partial void Onfl_NgayThemChanged();
    partial void Onfl_NgaySuaChanging(System.Nullable<System.DateTime> value);
    partial void Onfl_NgaySuaChanged();
    partial void Onfl_XoaChanging(int value);
    partial void Onfl_XoaChanged();
    #endregion
		
		public KhachHang()
		{
			this._VeXes = new EntitySet<VeXe>(new Action<VeXe>(this.attach_VeXes), new Action<VeXe>(this.detach_VeXes));
			this._TaiKhoan = default(EntityRef<TaiKhoan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhachHang", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKhachHang
		{
			get
			{
				return this._MaKhachHang;
			}
			set
			{
				if ((this._MaKhachHang != value))
				{
					this.OnMaKhachHangChanging(value);
					this.SendPropertyChanging();
					this._MaKhachHang = value;
					this.SendPropertyChanged("MaKhachHang");
					this.OnMaKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKhachHang", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenKhachHang
		{
			get
			{
				return this._TenKhachHang;
			}
			set
			{
				if ((this._TenKhachHang != value))
				{
					this.OnTenKhachHangChanging(value);
					this.SendPropertyChanging();
					this._TenKhachHang = value;
					this.SendPropertyChanged("TenKhachHang");
					this.OnTenKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(3)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoai", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string DienThoai
		{
			get
			{
				return this._DienThoai;
			}
			set
			{
				if ((this._DienThoai != value))
				{
					this.OnDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._DienThoai = value;
					this.SendPropertyChanged("DienThoai");
					this.OnDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CCCD", DbType="VarChar(15)")]
		public string CCCD
		{
			get
			{
				return this._CCCD;
			}
			set
			{
				if ((this._CCCD != value))
				{
					this.OnCCCDChanging(value);
					this.SendPropertyChanging();
					this._CCCD = value;
					this.SendPropertyChanged("CCCD");
					this.OnCCCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(500)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDangNhap", DbType="VarChar(50)")]
		public string TenDangNhap
		{
			get
			{
				return this._TenDangNhap;
			}
			set
			{
				if ((this._TenDangNhap != value))
				{
					if (this._TaiKhoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTenDangNhapChanging(value);
					this.SendPropertyChanging();
					this._TenDangNhap = value;
					this.SendPropertyChanged("TenDangNhap");
					this.OnTenDangNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fl_NgayThem", DbType="DateTime NOT NULL")]
		public System.DateTime fl_NgayThem
		{
			get
			{
				return this._fl_NgayThem;
			}
			set
			{
				if ((this._fl_NgayThem != value))
				{
					this.Onfl_NgayThemChanging(value);
					this.SendPropertyChanging();
					this._fl_NgayThem = value;
					this.SendPropertyChanged("fl_NgayThem");
					this.Onfl_NgayThemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fl_NgaySua", DbType="DateTime")]
		public System.Nullable<System.DateTime> fl_NgaySua
		{
			get
			{
				return this._fl_NgaySua;
			}
			set
			{
				if ((this._fl_NgaySua != value))
				{
					this.Onfl_NgaySuaChanging(value);
					this.SendPropertyChanging();
					this._fl_NgaySua = value;
					this.SendPropertyChanged("fl_NgaySua");
					this.Onfl_NgaySuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fl_Xoa", DbType="Int NOT NULL")]
		public int fl_Xoa
		{
			get
			{
				return this._fl_Xoa;
			}
			set
			{
				if ((this._fl_Xoa != value))
				{
					this.Onfl_XoaChanging(value);
					this.SendPropertyChanging();
					this._fl_Xoa = value;
					this.SendPropertyChanged("fl_Xoa");
					this.Onfl_XoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_VeXe", Storage="_VeXes", ThisKey="MaKhachHang", OtherKey="MaKhachHang")]
		public EntitySet<VeXe> VeXes
		{
			get
			{
				return this._VeXes;
			}
			set
			{
				this._VeXes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoan_KhachHang", Storage="_TaiKhoan", ThisKey="TenDangNhap", OtherKey="TenDangNhap", IsForeignKey=true)]
		public TaiKhoan TaiKhoan
		{
			get
			{
				return this._TaiKhoan.Entity;
			}
			set
			{
				TaiKhoan previousValue = this._TaiKhoan.Entity;
				if (((previousValue != value) 
							|| (this._TaiKhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TaiKhoan.Entity = null;
						previousValue.KhachHangs.Remove(this);
					}
					this._TaiKhoan.Entity = value;
					if ((value != null))
					{
						value.KhachHangs.Add(this);
						this._TenDangNhap = value.TenDangNhap;
					}
					else
					{
						this._TenDangNhap = default(string);
					}
					this.SendPropertyChanged("TaiKhoan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_VeXes(VeXe entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_VeXes(VeXe entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LichChay")]
	public partial class LichChay : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaLichChay;
		
		private System.DateTime _NgayKhoiHanh;
		
		private string _GioKhoiHanh;
		
		private string _MaLoTrinh;
		
		private string _MaNhanVien;
		
		private System.DateTime _fl_NgayThem;
		
		private System.Nullable<System.DateTime> _fl_NgaySua;
		
		private int _fl_Xoa;
		
		private EntitySet<LichChay_Xe> _LichChay_Xes;
		
		private EntityRef<LoTrinh> _LoTrinh;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLichChayChanging(string value);
    partial void OnMaLichChayChanged();
    partial void OnNgayKhoiHanhChanging(System.DateTime value);
    partial void OnNgayKhoiHanhChanged();
    partial void OnGioKhoiHanhChanging(string value);
    partial void OnGioKhoiHanhChanged();
    partial void OnMaLoTrinhChanging(string value);
    partial void OnMaLoTrinhChanged();
    partial void OnMaNhanVienChanging(string value);
    partial void OnMaNhanVienChanged();
    partial void Onfl_NgayThemChanging(System.DateTime value);
    partial void Onfl_NgayThemChanged();
    partial void Onfl_NgaySuaChanging(System.Nullable<System.DateTime> value);
    partial void Onfl_NgaySuaChanged();
    partial void Onfl_XoaChanging(int value);
    partial void Onfl_XoaChanged();
    #endregion
		
		public LichChay()
		{
			this._LichChay_Xes = new EntitySet<LichChay_Xe>(new Action<LichChay_Xe>(this.attach_LichChay_Xes), new Action<LichChay_Xe>(this.detach_LichChay_Xes));
			this._LoTrinh = default(EntityRef<LoTrinh>);
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLichChay", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLichChay
		{
			get
			{
				return this._MaLichChay;
			}
			set
			{
				if ((this._MaLichChay != value))
				{
					this.OnMaLichChayChanging(value);
					this.SendPropertyChanging();
					this._MaLichChay = value;
					this.SendPropertyChanged("MaLichChay");
					this.OnMaLichChayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKhoiHanh", DbType="DateTime NOT NULL")]
		public System.DateTime NgayKhoiHanh
		{
			get
			{
				return this._NgayKhoiHanh;
			}
			set
			{
				if ((this._NgayKhoiHanh != value))
				{
					this.OnNgayKhoiHanhChanging(value);
					this.SendPropertyChanging();
					this._NgayKhoiHanh = value;
					this.SendPropertyChanged("NgayKhoiHanh");
					this.OnNgayKhoiHanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioKhoiHanh", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string GioKhoiHanh
		{
			get
			{
				return this._GioKhoiHanh;
			}
			set
			{
				if ((this._GioKhoiHanh != value))
				{
					this.OnGioKhoiHanhChanging(value);
					this.SendPropertyChanging();
					this._GioKhoiHanh = value;
					this.SendPropertyChanged("GioKhoiHanh");
					this.OnGioKhoiHanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoTrinh", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MaLoTrinh
		{
			get
			{
				return this._MaLoTrinh;
			}
			set
			{
				if ((this._MaLoTrinh != value))
				{
					if (this._LoTrinh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLoTrinhChanging(value);
					this.SendPropertyChanging();
					this._MaLoTrinh = value;
					this.SendPropertyChanged("MaLoTrinh");
					this.OnMaLoTrinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhanVien", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MaNhanVien
		{
			get
			{
				return this._MaNhanVien;
			}
			set
			{
				if ((this._MaNhanVien != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._MaNhanVien = value;
					this.SendPropertyChanged("MaNhanVien");
					this.OnMaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fl_NgayThem", DbType="DateTime NOT NULL")]
		public System.DateTime fl_NgayThem
		{
			get
			{
				return this._fl_NgayThem;
			}
			set
			{
				if ((this._fl_NgayThem != value))
				{
					this.Onfl_NgayThemChanging(value);
					this.SendPropertyChanging();
					this._fl_NgayThem = value;
					this.SendPropertyChanged("fl_NgayThem");
					this.Onfl_NgayThemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fl_NgaySua", DbType="DateTime")]
		public System.Nullable<System.DateTime> fl_NgaySua
		{
			get
			{
				return this._fl_NgaySua;
			}
			set
			{
				if ((this._fl_NgaySua != value))
				{
					this.Onfl_NgaySuaChanging(value);
					this.SendPropertyChanging();
					this._fl_NgaySua = value;
					this.SendPropertyChanged("fl_NgaySua");
					this.Onfl_NgaySuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fl_Xoa", DbType="Int NOT NULL")]
		public int fl_Xoa
		{
			get
			{
				return this._fl_Xoa;
			}
			set
			{
				if ((this._fl_Xoa != value))
				{
					this.Onfl_XoaChanging(value);
					this.SendPropertyChanging();
					this._fl_Xoa = value;
					this.SendPropertyChanged("fl_Xoa");
					this.Onfl_XoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LichChay_LichChay_Xe", Storage="_LichChay_Xes", ThisKey="MaLichChay", OtherKey="MaLichChay")]
		public EntitySet<LichChay_Xe> LichChay_Xes
		{
			get
			{
				return this._LichChay_Xes;
			}
			set
			{
				this._LichChay_Xes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoTrinh_LichChay", Storage="_LoTrinh", ThisKey="MaLoTrinh", OtherKey="MaLoTrinh", IsForeignKey=true)]
		public LoTrinh LoTrinh
		{
			get
			{
				return this._LoTrinh.Entity;
			}
			set
			{
				LoTrinh previousValue = this._LoTrinh.Entity;
				if (((previousValue != value) 
							|| (this._LoTrinh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoTrinh.Entity = null;
						previousValue.LichChays.Remove(this);
					}
					this._LoTrinh.Entity = value;
					if ((value != null))
					{
						value.LichChays.Add(this);
						this._MaLoTrinh = value.MaLoTrinh;
					}
					else
					{
						this._MaLoTrinh = default(string);
					}
					this.SendPropertyChanged("LoTrinh");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_LichChay", Storage="_NhanVien", ThisKey="MaNhanVien", OtherKey="MaNhanVien", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.LichChays.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.LichChays.Add(this);
						this._MaNhanVien = value.MaNhanVien;
					}
					else
					{
						this._MaNhanVien = default(string);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_LichChay_Xes(LichChay_Xe entity)
		{
			this.SendPropertyChanging();
			entity.LichChay = this;
		}
		
		private void detach_LichChay_Xes(LichChay_Xe entity)
		{
			this.SendPropertyChanging();
			entity.LichChay = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LichChay_Xe")]
	public partial class LichChay_Xe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaLichChay_Xe;
		
		private int _TrangThai;
		
		private string _MaLichChay;
		
		private string _MaXe;
		
		private System.DateTime _fl_NgayThem;
		
		private System.Nullable<System.DateTime> _fl_NgaySua;
		
		private int _fl_Xoa;
		
		private EntitySet<VeXe> _VeXes;
		
		private EntityRef<LichChay> _LichChay;
		
		private EntityRef<Xe> _Xe;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLichChay_XeChanging(string value);
    partial void OnMaLichChay_XeChanged();
    partial void OnTrangThaiChanging(int value);
    partial void OnTrangThaiChanged();
    partial void OnMaLichChayChanging(string value);
    partial void OnMaLichChayChanged();
    partial void OnMaXeChanging(string value);
    partial void OnMaXeChanged();
    partial void Onfl_NgayThemChanging(System.DateTime value);
    partial void Onfl_NgayThemChanged();
    partial void Onfl_NgaySuaChanging(System.Nullable<System.DateTime> value);
    partial void Onfl_NgaySuaChanged();
    partial void Onfl_XoaChanging(int value);
    partial void Onfl_XoaChanged();
    #endregion
		
		public LichChay_Xe()
		{
			this._VeXes = new EntitySet<VeXe>(new Action<VeXe>(this.attach_VeXes), new Action<VeXe>(this.detach_VeXes));
			this._LichChay = default(EntityRef<LichChay>);
			this._Xe = default(EntityRef<Xe>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLichChay_Xe", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLichChay_Xe
		{
			get
			{
				return this._MaLichChay_Xe;
			}
			set
			{
				if ((this._MaLichChay_Xe != value))
				{
					this.OnMaLichChay_XeChanging(value);
					this.SendPropertyChanging();
					this._MaLichChay_Xe = value;
					this.SendPropertyChanged("MaLichChay_Xe");
					this.OnMaLichChay_XeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="Int NOT NULL")]
		public int TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLichChay", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MaLichChay
		{
			get
			{
				return this._MaLichChay;
			}
			set
			{
				if ((this._MaLichChay != value))
				{
					if (this._LichChay.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLichChayChanging(value);
					this.SendPropertyChanging();
					this._MaLichChay = value;
					this.SendPropertyChanged("MaLichChay");
					this.OnMaLichChayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaXe", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MaXe
		{
			get
			{
				return this._MaXe;
			}
			set
			{
				if ((this._MaXe != value))
				{
					if (this._Xe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaXeChanging(value);
					this.SendPropertyChanging();
					this._MaXe = value;
					this.SendPropertyChanged("MaXe");
					this.OnMaXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fl_NgayThem", DbType="DateTime NOT NULL")]
		public System.DateTime fl_NgayThem
		{
			get
			{
				return this._fl_NgayThem;
			}
			set
			{
				if ((this._fl_NgayThem != value))
				{
					this.Onfl_NgayThemChanging(value);
					this.SendPropertyChanging();
					this._fl_NgayThem = value;
					this.SendPropertyChanged("fl_NgayThem");
					this.Onfl_NgayThemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fl_NgaySua", DbType="DateTime")]
		public System.Nullable<System.DateTime> fl_NgaySua
		{
			get
			{
				return this._fl_NgaySua;
			}
			set
			{
				if ((this._fl_NgaySua != value))
				{
					this.Onfl_NgaySuaChanging(value);
					this.SendPropertyChanging();
					this._fl_NgaySua = value;
					this.SendPropertyChanged("fl_NgaySua");
					this.Onfl_NgaySuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fl_Xoa", DbType="Int NOT NULL")]
		public int fl_Xoa
		{
			get
			{
				return this._fl_Xoa;
			}
			set
			{
				if ((this._fl_Xoa != value))
				{
					this.Onfl_XoaChanging(value);
					this.SendPropertyChanging();
					this._fl_Xoa = value;
					this.SendPropertyChanged("fl_Xoa");
					this.Onfl_XoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LichChay_Xe_VeXe", Storage="_VeXes", ThisKey="MaLichChay_Xe", OtherKey="MaLichChay_Xe")]
		public EntitySet<VeXe> VeXes
		{
			get
			{
				return this._VeXes;
			}
			set
			{
				this._VeXes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LichChay_LichChay_Xe", Storage="_LichChay", ThisKey="MaLichChay", OtherKey="MaLichChay", IsForeignKey=true)]
		public LichChay LichChay
		{
			get
			{
				return this._LichChay.Entity;
			}
			set
			{
				LichChay previousValue = this._LichChay.Entity;
				if (((previousValue != value) 
							|| (this._LichChay.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LichChay.Entity = null;
						previousValue.LichChay_Xes.Remove(this);
					}
					this._LichChay.Entity = value;
					if ((value != null))
					{
						value.LichChay_Xes.Add(this);
						this._MaLichChay = value.MaLichChay;
					}
					else
					{
						this._MaLichChay = default(string);
					}
					this.SendPropertyChanged("LichChay");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Xe_LichChay_Xe", Storage="_Xe", ThisKey="MaXe", OtherKey="MaXe", IsForeignKey=true)]
		public Xe Xe
		{
			get
			{
				return this._Xe.Entity;
			}
			set
			{
				Xe previousValue = this._Xe.Entity;
				if (((previousValue != value) 
							|| (this._Xe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Xe.Entity = null;
						previousValue.LichChay_Xes.Remove(this);
					}
					this._Xe.Entity = value;
					if ((value != null))
					{
						value.LichChay_Xes.Add(this);
						this._MaXe = value.MaXe;
					}
					else
					{
						this._MaXe = default(string);
					}
					this.SendPropertyChanged("Xe");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_VeXes(VeXe entity)
		{
			this.SendPropertyChanging();
			entity.LichChay_Xe = this;
		}
		
		private void detach_VeXes(VeXe entity)
		{
			this.SendPropertyChanging();
			entity.LichChay_Xe = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiNhanVien")]
	public partial class LoaiNhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaLoaiNhanVien;
		
		private string _TenLoaiNhanVien;
		
		private int _fl_Xoa;
		
		private EntitySet<NhanVien> _NhanViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLoaiNhanVienChanging(int value);
    partial void OnMaLoaiNhanVienChanged();
    partial void OnTenLoaiNhanVienChanging(string value);
    partial void OnTenLoaiNhanVienChanged();
    partial void Onfl_XoaChanging(int value);
    partial void Onfl_XoaChanged();
    #endregion
		
		public LoaiNhanVien()
		{
			this._NhanViens = new EntitySet<NhanVien>(new Action<NhanVien>(this.attach_NhanViens), new Action<NhanVien>(this.detach_NhanViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiNhanVien", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaLoaiNhanVien
		{
			get
			{
				return this._MaLoaiNhanVien;
			}
			set
			{
				if ((this._MaLoaiNhanVien != value))
				{
					this.OnMaLoaiNhanVienChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiNhanVien = value;
					this.SendPropertyChanged("MaLoaiNhanVien");
					this.OnMaLoaiNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoaiNhanVien", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenLoaiNhanVien
		{
			get
			{
				return this._TenLoaiNhanVien;
			}
			set
			{
				if ((this._TenLoaiNhanVien != value))
				{
					this.OnTenLoaiNhanVienChanging(value);
					this.SendPropertyChanging();
					this._TenLoaiNhanVien = value;
					this.SendPropertyChanged("TenLoaiNhanVien");
					this.OnTenLoaiNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fl_Xoa", DbType="Int NOT NULL")]
		public int fl_Xoa
		{
			get
			{
				return this._fl_Xoa;
			}
			set
			{
				if ((this._fl_Xoa != value))
				{
					this.Onfl_XoaChanging(value);
					this.SendPropertyChanging();
					this._fl_Xoa = value;
					this.SendPropertyChanged("fl_Xoa");
					this.Onfl_XoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiNhanVien_NhanVien", Storage="_NhanViens", ThisKey="MaLoaiNhanVien", OtherKey="MaLoaiNhanVien")]
		public EntitySet<NhanVien> NhanViens
		{
			get
			{
				return this._NhanViens;
			}
			set
			{
				this._NhanViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NhanViens(NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.LoaiNhanVien = this;
		}
		
		private void detach_NhanViens(NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.LoaiNhanVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiTaiKhoan")]
	public partial class LoaiTaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaLoaiTaiKhoan;
		
		private string _TenLoaiTaiKhoan;
		
		private int _fl_Xoa;
		
		private EntitySet<TaiKhoan> _TaiKhoans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLoaiTaiKhoanChanging(int value);
    partial void OnMaLoaiTaiKhoanChanged();
    partial void OnTenLoaiTaiKhoanChanging(string value);
    partial void OnTenLoaiTaiKhoanChanged();
    partial void Onfl_XoaChanging(int value);
    partial void Onfl_XoaChanged();
    #endregion
		
		public LoaiTaiKhoan()
		{
			this._TaiKhoans = new EntitySet<TaiKhoan>(new Action<TaiKhoan>(this.attach_TaiKhoans), new Action<TaiKhoan>(this.detach_TaiKhoans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiTaiKhoan", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaLoaiTaiKhoan
		{
			get
			{
				return this._MaLoaiTaiKhoan;
			}
			set
			{
				if ((this._MaLoaiTaiKhoan != value))
				{
					this.OnMaLoaiTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiTaiKhoan = value;
					this.SendPropertyChanged("MaLoaiTaiKhoan");
					this.OnMaLoaiTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoaiTaiKhoan", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenLoaiTaiKhoan
		{
			get
			{
				return this._TenLoaiTaiKhoan;
			}
			set
			{
				if ((this._TenLoaiTaiKhoan != value))
				{
					this.OnTenLoaiTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._TenLoaiTaiKhoan = value;
					this.SendPropertyChanged("TenLoaiTaiKhoan");
					this.OnTenLoaiTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fl_Xoa", DbType="Int NOT NULL")]
		public int fl_Xoa
		{
			get
			{
				return this._fl_Xoa;
			}
			set
			{
				if ((this._fl_Xoa != value))
				{
					this.Onfl_XoaChanging(value);
					this.SendPropertyChanging();
					this._fl_Xoa = value;
					this.SendPropertyChanged("fl_Xoa");
					this.Onfl_XoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiTaiKhoan_TaiKhoan", Storage="_TaiKhoans", ThisKey="MaLoaiTaiKhoan", OtherKey="MaLoaiTaiKhoan")]
		public EntitySet<TaiKhoan> TaiKhoans
		{
			get
			{
				return this._TaiKhoans;
			}
			set
			{
				this._TaiKhoans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TaiKhoans(TaiKhoan entity)
		{
			this.SendPropertyChanging();
			entity.LoaiTaiKhoan = this;
		}
		
		private void detach_TaiKhoans(TaiKhoan entity)
		{
			this.SendPropertyChanging();
			entity.LoaiTaiKhoan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiXe")]
	public partial class LoaiXe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaLoaiXe;
		
		private string _TenLoaiXe;
		
		private int _fl_Xoa;
		
		private EntitySet<Xe> _Xes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLoaiXeChanging(int value);
    partial void OnMaLoaiXeChanged();
    partial void OnTenLoaiXeChanging(string value);
    partial void OnTenLoaiXeChanged();
    partial void Onfl_XoaChanging(int value);
    partial void Onfl_XoaChanged();
    #endregion
		
		public LoaiXe()
		{
			this._Xes = new EntitySet<Xe>(new Action<Xe>(this.attach_Xes), new Action<Xe>(this.detach_Xes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiXe", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaLoaiXe
		{
			get
			{
				return this._MaLoaiXe;
			}
			set
			{
				if ((this._MaLoaiXe != value))
				{
					this.OnMaLoaiXeChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiXe = value;
					this.SendPropertyChanged("MaLoaiXe");
					this.OnMaLoaiXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoaiXe", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenLoaiXe
		{
			get
			{
				return this._TenLoaiXe;
			}
			set
			{
				if ((this._TenLoaiXe != value))
				{
					this.OnTenLoaiXeChanging(value);
					this.SendPropertyChanging();
					this._TenLoaiXe = value;
					this.SendPropertyChanged("TenLoaiXe");
					this.OnTenLoaiXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fl_Xoa", DbType="Int NOT NULL")]
		public int fl_Xoa
		{
			get
			{
				return this._fl_Xoa;
			}
			set
			{
				if ((this._fl_Xoa != value))
				{
					this.Onfl_XoaChanging(value);
					this.SendPropertyChanging();
					this._fl_Xoa = value;
					this.SendPropertyChanged("fl_Xoa");
					this.Onfl_XoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiXe_Xe", Storage="_Xes", ThisKey="MaLoaiXe", OtherKey="MaLoaiXe")]
		public EntitySet<Xe> Xes
		{
			get
			{
				return this._Xes;
			}
			set
			{
				this._Xes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Xes(Xe entity)
		{
			this.SendPropertyChanging();
			entity.LoaiXe = this;
		}
		
		private void detach_Xes(Xe entity)
		{
			this.SendPropertyChanging();
			entity.LoaiXe = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoTrinh")]
	public partial class LoTrinh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaLoTrinh;
		
		private string _DiemDi;
		
		private string _DiemDen;
		
		private int _QuangDuong;
		
		private int _GiaVe;
		
		private System.DateTime _fl_NgayThem;
		
		private System.Nullable<System.DateTime> _fl_NgaySua;
		
		private int _fl_Xoa;
		
		private EntitySet<LichChay> _LichChays;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLoTrinhChanging(string value);
    partial void OnMaLoTrinhChanged();
    partial void OnDiemDiChanging(string value);
    partial void OnDiemDiChanged();
    partial void OnDiemDenChanging(string value);
    partial void OnDiemDenChanged();
    partial void OnQuangDuongChanging(int value);
    partial void OnQuangDuongChanged();
    partial void OnGiaVeChanging(int value);
    partial void OnGiaVeChanged();
    partial void Onfl_NgayThemChanging(System.DateTime value);
    partial void Onfl_NgayThemChanged();
    partial void Onfl_NgaySuaChanging(System.Nullable<System.DateTime> value);
    partial void Onfl_NgaySuaChanged();
    partial void Onfl_XoaChanging(int value);
    partial void Onfl_XoaChanged();
    #endregion
		
		public LoTrinh()
		{
			this._LichChays = new EntitySet<LichChay>(new Action<LichChay>(this.attach_LichChays), new Action<LichChay>(this.detach_LichChays));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoTrinh", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLoTrinh
		{
			get
			{
				return this._MaLoTrinh;
			}
			set
			{
				if ((this._MaLoTrinh != value))
				{
					this.OnMaLoTrinhChanging(value);
					this.SendPropertyChanging();
					this._MaLoTrinh = value;
					this.SendPropertyChanged("MaLoTrinh");
					this.OnMaLoTrinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiemDi", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string DiemDi
		{
			get
			{
				return this._DiemDi;
			}
			set
			{
				if ((this._DiemDi != value))
				{
					this.OnDiemDiChanging(value);
					this.SendPropertyChanging();
					this._DiemDi = value;
					this.SendPropertyChanged("DiemDi");
					this.OnDiemDiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiemDen", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string DiemDen
		{
			get
			{
				return this._DiemDen;
			}
			set
			{
				if ((this._DiemDen != value))
				{
					this.OnDiemDenChanging(value);
					this.SendPropertyChanging();
					this._DiemDen = value;
					this.SendPropertyChanged("DiemDen");
					this.OnDiemDenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuangDuong", DbType="Int NOT NULL")]
		public int QuangDuong
		{
			get
			{
				return this._QuangDuong;
			}
			set
			{
				if ((this._QuangDuong != value))
				{
					this.OnQuangDuongChanging(value);
					this.SendPropertyChanging();
					this._QuangDuong = value;
					this.SendPropertyChanged("QuangDuong");
					this.OnQuangDuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaVe", DbType="Int NOT NULL")]
		public int GiaVe
		{
			get
			{
				return this._GiaVe;
			}
			set
			{
				if ((this._GiaVe != value))
				{
					this.OnGiaVeChanging(value);
					this.SendPropertyChanging();
					this._GiaVe = value;
					this.SendPropertyChanged("GiaVe");
					this.OnGiaVeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fl_NgayThem", DbType="DateTime NOT NULL")]
		public System.DateTime fl_NgayThem
		{
			get
			{
				return this._fl_NgayThem;
			}
			set
			{
				if ((this._fl_NgayThem != value))
				{
					this.Onfl_NgayThemChanging(value);
					this.SendPropertyChanging();
					this._fl_NgayThem = value;
					this.SendPropertyChanged("fl_NgayThem");
					this.Onfl_NgayThemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fl_NgaySua", DbType="DateTime")]
		public System.Nullable<System.DateTime> fl_NgaySua
		{
			get
			{
				return this._fl_NgaySua;
			}
			set
			{
				if ((this._fl_NgaySua != value))
				{
					this.Onfl_NgaySuaChanging(value);
					this.SendPropertyChanging();
					this._fl_NgaySua = value;
					this.SendPropertyChanged("fl_NgaySua");
					this.Onfl_NgaySuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fl_Xoa", DbType="Int NOT NULL")]
		public int fl_Xoa
		{
			get
			{
				return this._fl_Xoa;
			}
			set
			{
				if ((this._fl_Xoa != value))
				{
					this.Onfl_XoaChanging(value);
					this.SendPropertyChanging();
					this._fl_Xoa = value;
					this.SendPropertyChanged("fl_Xoa");
					this.Onfl_XoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoTrinh_LichChay", Storage="_LichChays", ThisKey="MaLoTrinh", OtherKey="MaLoTrinh")]
		public EntitySet<LichChay> LichChays
		{
			get
			{
				return this._LichChays;
			}
			set
			{
				this._LichChays.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_LichChays(LichChay entity)
		{
			this.SendPropertyChanging();
			entity.LoTrinh = this;
		}
		
		private void detach_LichChays(LichChay entity)
		{
			this.SendPropertyChanging();
			entity.LoTrinh = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhanVien")]
	public partial class NhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNhanVien;
		
		private string _TenNhanVien;
		
		private string _GioiTinh;
		
		private System.DateTime _NgaySinh;
		
		private string _DienThoai;
		
		private string _CCCD;
		
		private string _DiaChi;
		
		private int _MaLoaiNhanVien;
		
		private string _TenDangNhap;
		
		private System.DateTime _fl_NgayThem;
		
		private System.Nullable<System.DateTime> _fl_NgaySua;
		
		private int _fl_Xoa;
		
		private EntitySet<LichChay> _LichChays;
		
		private EntitySet<VeXe> _VeXes;
		
		private EntityRef<LoaiNhanVien> _LoaiNhanVien;
		
		private EntityRef<TaiKhoan> _TaiKhoan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNhanVienChanging(string value);
    partial void OnMaNhanVienChanged();
    partial void OnTenNhanVienChanging(string value);
    partial void OnTenNhanVienChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnNgaySinhChanging(System.DateTime value);
    partial void OnNgaySinhChanged();
    partial void OnDienThoaiChanging(string value);
    partial void OnDienThoaiChanged();
    partial void OnCCCDChanging(string value);
    partial void OnCCCDChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnMaLoaiNhanVienChanging(int value);
    partial void OnMaLoaiNhanVienChanged();
    partial void OnTenDangNhapChanging(string value);
    partial void OnTenDangNhapChanged();
    partial void Onfl_NgayThemChanging(System.DateTime value);
    partial void Onfl_NgayThemChanged();
    partial void Onfl_NgaySuaChanging(System.Nullable<System.DateTime> value);
    partial void Onfl_NgaySuaChanged();
    partial void Onfl_XoaChanging(int value);
    partial void Onfl_XoaChanged();
    #endregion
		
		public NhanVien()
		{
			this._LichChays = new EntitySet<LichChay>(new Action<LichChay>(this.attach_LichChays), new Action<LichChay>(this.detach_LichChays));
			this._VeXes = new EntitySet<VeXe>(new Action<VeXe>(this.attach_VeXes), new Action<VeXe>(this.detach_VeXes));
			this._LoaiNhanVien = default(EntityRef<LoaiNhanVien>);
			this._TaiKhoan = default(EntityRef<TaiKhoan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhanVien", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNhanVien
		{
			get
			{
				return this._MaNhanVien;
			}
			set
			{
				if ((this._MaNhanVien != value))
				{
					this.OnMaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._MaNhanVien = value;
					this.SendPropertyChanged("MaNhanVien");
					this.OnMaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNhanVien", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenNhanVien
		{
			get
			{
				return this._TenNhanVien;
			}
			set
			{
				if ((this._TenNhanVien != value))
				{
					this.OnTenNhanVienChanging(value);
					this.SendPropertyChanging();
					this._TenNhanVien = value;
					this.SendPropertyChanged("TenNhanVien");
					this.OnTenNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(3) NOT NULL", CanBeNull=false)]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="DateTime NOT NULL")]
		public System.DateTime NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoai", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string DienThoai
		{
			get
			{
				return this._DienThoai;
			}
			set
			{
				if ((this._DienThoai != value))
				{
					this.OnDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._DienThoai = value;
					this.SendPropertyChanged("DienThoai");
					this.OnDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CCCD", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string CCCD
		{
			get
			{
				return this._CCCD;
			}
			set
			{
				if ((this._CCCD != value))
				{
					this.OnCCCDChanging(value);
					this.SendPropertyChanging();
					this._CCCD = value;
					this.SendPropertyChanged("CCCD");
					this.OnCCCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiNhanVien", DbType="Int NOT NULL")]
		public int MaLoaiNhanVien
		{
			get
			{
				return this._MaLoaiNhanVien;
			}
			set
			{
				if ((this._MaLoaiNhanVien != value))
				{
					if (this._LoaiNhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLoaiNhanVienChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiNhanVien = value;
					this.SendPropertyChanged("MaLoaiNhanVien");
					this.OnMaLoaiNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDangNhap", DbType="VarChar(50)")]
		public string TenDangNhap
		{
			get
			{
				return this._TenDangNhap;
			}
			set
			{
				if ((this._TenDangNhap != value))
				{
					if (this._TaiKhoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTenDangNhapChanging(value);
					this.SendPropertyChanging();
					this._TenDangNhap = value;
					this.SendPropertyChanged("TenDangNhap");
					this.OnTenDangNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fl_NgayThem", DbType="DateTime NOT NULL")]
		public System.DateTime fl_NgayThem
		{
			get
			{
				return this._fl_NgayThem;
			}
			set
			{
				if ((this._fl_NgayThem != value))
				{
					this.Onfl_NgayThemChanging(value);
					this.SendPropertyChanging();
					this._fl_NgayThem = value;
					this.SendPropertyChanged("fl_NgayThem");
					this.Onfl_NgayThemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fl_NgaySua", DbType="DateTime")]
		public System.Nullable<System.DateTime> fl_NgaySua
		{
			get
			{
				return this._fl_NgaySua;
			}
			set
			{
				if ((this._fl_NgaySua != value))
				{
					this.Onfl_NgaySuaChanging(value);
					this.SendPropertyChanging();
					this._fl_NgaySua = value;
					this.SendPropertyChanged("fl_NgaySua");
					this.Onfl_NgaySuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fl_Xoa", DbType="Int NOT NULL")]
		public int fl_Xoa
		{
			get
			{
				return this._fl_Xoa;
			}
			set
			{
				if ((this._fl_Xoa != value))
				{
					this.Onfl_XoaChanging(value);
					this.SendPropertyChanging();
					this._fl_Xoa = value;
					this.SendPropertyChanged("fl_Xoa");
					this.Onfl_XoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_LichChay", Storage="_LichChays", ThisKey="MaNhanVien", OtherKey="MaNhanVien")]
		public EntitySet<LichChay> LichChays
		{
			get
			{
				return this._LichChays;
			}
			set
			{
				this._LichChays.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_VeXe", Storage="_VeXes", ThisKey="MaNhanVien", OtherKey="MaNhanVien")]
		public EntitySet<VeXe> VeXes
		{
			get
			{
				return this._VeXes;
			}
			set
			{
				this._VeXes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiNhanVien_NhanVien", Storage="_LoaiNhanVien", ThisKey="MaLoaiNhanVien", OtherKey="MaLoaiNhanVien", IsForeignKey=true)]
		public LoaiNhanVien LoaiNhanVien
		{
			get
			{
				return this._LoaiNhanVien.Entity;
			}
			set
			{
				LoaiNhanVien previousValue = this._LoaiNhanVien.Entity;
				if (((previousValue != value) 
							|| (this._LoaiNhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiNhanVien.Entity = null;
						previousValue.NhanViens.Remove(this);
					}
					this._LoaiNhanVien.Entity = value;
					if ((value != null))
					{
						value.NhanViens.Add(this);
						this._MaLoaiNhanVien = value.MaLoaiNhanVien;
					}
					else
					{
						this._MaLoaiNhanVien = default(int);
					}
					this.SendPropertyChanged("LoaiNhanVien");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoan_NhanVien", Storage="_TaiKhoan", ThisKey="TenDangNhap", OtherKey="TenDangNhap", IsForeignKey=true)]
		public TaiKhoan TaiKhoan
		{
			get
			{
				return this._TaiKhoan.Entity;
			}
			set
			{
				TaiKhoan previousValue = this._TaiKhoan.Entity;
				if (((previousValue != value) 
							|| (this._TaiKhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TaiKhoan.Entity = null;
						previousValue.NhanViens.Remove(this);
					}
					this._TaiKhoan.Entity = value;
					if ((value != null))
					{
						value.NhanViens.Add(this);
						this._TenDangNhap = value.TenDangNhap;
					}
					else
					{
						this._TenDangNhap = default(string);
					}
					this.SendPropertyChanged("TaiKhoan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_LichChays(LichChay entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_LichChays(LichChay entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
		
		private void attach_VeXes(VeXe entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_VeXes(VeXe entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaiKhoan")]
	public partial class TaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TenDangNhap;
		
		private string _MatKhau;
		
		private int _MaLoaiTaiKhoan;
		
		private System.DateTime _fl_NgayThem;
		
		private System.Nullable<System.DateTime> _fl_NgaySua;
		
		private int _fl_Xoa;
		
		private EntitySet<KhachHang> _KhachHangs;
		
		private EntitySet<NhanVien> _NhanViens;
		
		private EntityRef<LoaiTaiKhoan> _LoaiTaiKhoan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTenDangNhapChanging(string value);
    partial void OnTenDangNhapChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnMaLoaiTaiKhoanChanging(int value);
    partial void OnMaLoaiTaiKhoanChanged();
    partial void Onfl_NgayThemChanging(System.DateTime value);
    partial void Onfl_NgayThemChanged();
    partial void Onfl_NgaySuaChanging(System.Nullable<System.DateTime> value);
    partial void Onfl_NgaySuaChanged();
    partial void Onfl_XoaChanging(int value);
    partial void Onfl_XoaChanged();
    #endregion
		
		public TaiKhoan()
		{
			this._KhachHangs = new EntitySet<KhachHang>(new Action<KhachHang>(this.attach_KhachHangs), new Action<KhachHang>(this.detach_KhachHangs));
			this._NhanViens = new EntitySet<NhanVien>(new Action<NhanVien>(this.attach_NhanViens), new Action<NhanVien>(this.detach_NhanViens));
			this._LoaiTaiKhoan = default(EntityRef<LoaiTaiKhoan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDangNhap", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TenDangNhap
		{
			get
			{
				return this._TenDangNhap;
			}
			set
			{
				if ((this._TenDangNhap != value))
				{
					this.OnTenDangNhapChanging(value);
					this.SendPropertyChanging();
					this._TenDangNhap = value;
					this.SendPropertyChanged("TenDangNhap");
					this.OnTenDangNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="VarChar(1000) NOT NULL", CanBeNull=false)]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiTaiKhoan", DbType="Int NOT NULL")]
		public int MaLoaiTaiKhoan
		{
			get
			{
				return this._MaLoaiTaiKhoan;
			}
			set
			{
				if ((this._MaLoaiTaiKhoan != value))
				{
					if (this._LoaiTaiKhoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLoaiTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiTaiKhoan = value;
					this.SendPropertyChanged("MaLoaiTaiKhoan");
					this.OnMaLoaiTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fl_NgayThem", DbType="DateTime NOT NULL")]
		public System.DateTime fl_NgayThem
		{
			get
			{
				return this._fl_NgayThem;
			}
			set
			{
				if ((this._fl_NgayThem != value))
				{
					this.Onfl_NgayThemChanging(value);
					this.SendPropertyChanging();
					this._fl_NgayThem = value;
					this.SendPropertyChanged("fl_NgayThem");
					this.Onfl_NgayThemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fl_NgaySua", DbType="DateTime")]
		public System.Nullable<System.DateTime> fl_NgaySua
		{
			get
			{
				return this._fl_NgaySua;
			}
			set
			{
				if ((this._fl_NgaySua != value))
				{
					this.Onfl_NgaySuaChanging(value);
					this.SendPropertyChanging();
					this._fl_NgaySua = value;
					this.SendPropertyChanged("fl_NgaySua");
					this.Onfl_NgaySuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fl_Xoa", DbType="Int NOT NULL")]
		public int fl_Xoa
		{
			get
			{
				return this._fl_Xoa;
			}
			set
			{
				if ((this._fl_Xoa != value))
				{
					this.Onfl_XoaChanging(value);
					this.SendPropertyChanging();
					this._fl_Xoa = value;
					this.SendPropertyChanged("fl_Xoa");
					this.Onfl_XoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoan_KhachHang", Storage="_KhachHangs", ThisKey="TenDangNhap", OtherKey="TenDangNhap")]
		public EntitySet<KhachHang> KhachHangs
		{
			get
			{
				return this._KhachHangs;
			}
			set
			{
				this._KhachHangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoan_NhanVien", Storage="_NhanViens", ThisKey="TenDangNhap", OtherKey="TenDangNhap")]
		public EntitySet<NhanVien> NhanViens
		{
			get
			{
				return this._NhanViens;
			}
			set
			{
				this._NhanViens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiTaiKhoan_TaiKhoan", Storage="_LoaiTaiKhoan", ThisKey="MaLoaiTaiKhoan", OtherKey="MaLoaiTaiKhoan", IsForeignKey=true)]
		public LoaiTaiKhoan LoaiTaiKhoan
		{
			get
			{
				return this._LoaiTaiKhoan.Entity;
			}
			set
			{
				LoaiTaiKhoan previousValue = this._LoaiTaiKhoan.Entity;
				if (((previousValue != value) 
							|| (this._LoaiTaiKhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiTaiKhoan.Entity = null;
						previousValue.TaiKhoans.Remove(this);
					}
					this._LoaiTaiKhoan.Entity = value;
					if ((value != null))
					{
						value.TaiKhoans.Add(this);
						this._MaLoaiTaiKhoan = value.MaLoaiTaiKhoan;
					}
					else
					{
						this._MaLoaiTaiKhoan = default(int);
					}
					this.SendPropertyChanged("LoaiTaiKhoan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KhachHangs(KhachHang entity)
		{
			this.SendPropertyChanging();
			entity.TaiKhoan = this;
		}
		
		private void detach_KhachHangs(KhachHang entity)
		{
			this.SendPropertyChanging();
			entity.TaiKhoan = null;
		}
		
		private void attach_NhanViens(NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.TaiKhoan = this;
		}
		
		private void detach_NhanViens(NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.TaiKhoan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TrungChuyen")]
	public partial class TrungChuyen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTrungChuyen;
		
		private string _DiemDi;
		
		private string _DiemDen;
		
		private int _QuangDuong;
		
		private string _MaDiaChiTrungChuyen;
		
		private int _fl_Xoa;
		
		private EntityRef<DiaChiTrungChuyen> _DiaChiTrungChuyen;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTrungChuyenChanging(string value);
    partial void OnMaTrungChuyenChanged();
    partial void OnDiemDiChanging(string value);
    partial void OnDiemDiChanged();
    partial void OnDiemDenChanging(string value);
    partial void OnDiemDenChanged();
    partial void OnQuangDuongChanging(int value);
    partial void OnQuangDuongChanged();
    partial void OnMaDiaChiTrungChuyenChanging(string value);
    partial void OnMaDiaChiTrungChuyenChanged();
    partial void Onfl_XoaChanging(int value);
    partial void Onfl_XoaChanged();
    #endregion
		
		public TrungChuyen()
		{
			this._DiaChiTrungChuyen = default(EntityRef<DiaChiTrungChuyen>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTrungChuyen", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTrungChuyen
		{
			get
			{
				return this._MaTrungChuyen;
			}
			set
			{
				if ((this._MaTrungChuyen != value))
				{
					this.OnMaTrungChuyenChanging(value);
					this.SendPropertyChanging();
					this._MaTrungChuyen = value;
					this.SendPropertyChanged("MaTrungChuyen");
					this.OnMaTrungChuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiemDi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DiemDi
		{
			get
			{
				return this._DiemDi;
			}
			set
			{
				if ((this._DiemDi != value))
				{
					this.OnDiemDiChanging(value);
					this.SendPropertyChanging();
					this._DiemDi = value;
					this.SendPropertyChanged("DiemDi");
					this.OnDiemDiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiemDen", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DiemDen
		{
			get
			{
				return this._DiemDen;
			}
			set
			{
				if ((this._DiemDen != value))
				{
					this.OnDiemDenChanging(value);
					this.SendPropertyChanging();
					this._DiemDen = value;
					this.SendPropertyChanged("DiemDen");
					this.OnDiemDenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuangDuong", DbType="Int NOT NULL")]
		public int QuangDuong
		{
			get
			{
				return this._QuangDuong;
			}
			set
			{
				if ((this._QuangDuong != value))
				{
					this.OnQuangDuongChanging(value);
					this.SendPropertyChanging();
					this._QuangDuong = value;
					this.SendPropertyChanged("QuangDuong");
					this.OnQuangDuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDiaChiTrungChuyen", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MaDiaChiTrungChuyen
		{
			get
			{
				return this._MaDiaChiTrungChuyen;
			}
			set
			{
				if ((this._MaDiaChiTrungChuyen != value))
				{
					if (this._DiaChiTrungChuyen.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDiaChiTrungChuyenChanging(value);
					this.SendPropertyChanging();
					this._MaDiaChiTrungChuyen = value;
					this.SendPropertyChanged("MaDiaChiTrungChuyen");
					this.OnMaDiaChiTrungChuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fl_Xoa", DbType="Int NOT NULL")]
		public int fl_Xoa
		{
			get
			{
				return this._fl_Xoa;
			}
			set
			{
				if ((this._fl_Xoa != value))
				{
					this.Onfl_XoaChanging(value);
					this.SendPropertyChanging();
					this._fl_Xoa = value;
					this.SendPropertyChanged("fl_Xoa");
					this.Onfl_XoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DiaChiTrungChuyen_TrungChuyen", Storage="_DiaChiTrungChuyen", ThisKey="MaDiaChiTrungChuyen", OtherKey="MaDiaChiTrungChuyen", IsForeignKey=true)]
		public DiaChiTrungChuyen DiaChiTrungChuyen
		{
			get
			{
				return this._DiaChiTrungChuyen.Entity;
			}
			set
			{
				DiaChiTrungChuyen previousValue = this._DiaChiTrungChuyen.Entity;
				if (((previousValue != value) 
							|| (this._DiaChiTrungChuyen.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DiaChiTrungChuyen.Entity = null;
						previousValue.TrungChuyens.Remove(this);
					}
					this._DiaChiTrungChuyen.Entity = value;
					if ((value != null))
					{
						value.TrungChuyens.Add(this);
						this._MaDiaChiTrungChuyen = value.MaDiaChiTrungChuyen;
					}
					else
					{
						this._MaDiaChiTrungChuyen = default(string);
					}
					this.SendPropertyChanged("DiaChiTrungChuyen");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VeXe")]
	public partial class VeXe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaVeXe;
		
		private int _DonGia;
		
		private int _SoLuong;
		
		private int _ThanhTien;
		
		private string _MaNhanVien;
		
		private string _MaKhachHang;
		
		private string _MaLichChay_Xe;
		
		private int _fl_Xoa;
		
		private EntitySet<ChiTietVeXe> _ChiTietVeXes;
		
		private EntityRef<KhachHang> _KhachHang;
		
		private EntityRef<LichChay_Xe> _LichChay_Xe;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaVeXeChanging(string value);
    partial void OnMaVeXeChanged();
    partial void OnDonGiaChanging(int value);
    partial void OnDonGiaChanged();
    partial void OnSoLuongChanging(int value);
    partial void OnSoLuongChanged();
    partial void OnThanhTienChanging(int value);
    partial void OnThanhTienChanged();
    partial void OnMaNhanVienChanging(string value);
    partial void OnMaNhanVienChanged();
    partial void OnMaKhachHangChanging(string value);
    partial void OnMaKhachHangChanged();
    partial void OnMaLichChay_XeChanging(string value);
    partial void OnMaLichChay_XeChanged();
    partial void Onfl_XoaChanging(int value);
    partial void Onfl_XoaChanged();
    #endregion
		
		public VeXe()
		{
			this._ChiTietVeXes = new EntitySet<ChiTietVeXe>(new Action<ChiTietVeXe>(this.attach_ChiTietVeXes), new Action<ChiTietVeXe>(this.detach_ChiTietVeXes));
			this._KhachHang = default(EntityRef<KhachHang>);
			this._LichChay_Xe = default(EntityRef<LichChay_Xe>);
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaVeXe", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaVeXe
		{
			get
			{
				return this._MaVeXe;
			}
			set
			{
				if ((this._MaVeXe != value))
				{
					this.OnMaVeXeChanging(value);
					this.SendPropertyChanging();
					this._MaVeXe = value;
					this.SendPropertyChanged("MaVeXe");
					this.OnMaVeXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Int NOT NULL")]
		public int DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this.OnDonGiaChanging(value);
					this.SendPropertyChanging();
					this._DonGia = value;
					this.SendPropertyChanged("DonGia");
					this.OnDonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int NOT NULL")]
		public int SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThanhTien", DbType="Int NOT NULL")]
		public int ThanhTien
		{
			get
			{
				return this._ThanhTien;
			}
			set
			{
				if ((this._ThanhTien != value))
				{
					this.OnThanhTienChanging(value);
					this.SendPropertyChanging();
					this._ThanhTien = value;
					this.SendPropertyChanged("ThanhTien");
					this.OnThanhTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhanVien", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MaNhanVien
		{
			get
			{
				return this._MaNhanVien;
			}
			set
			{
				if ((this._MaNhanVien != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._MaNhanVien = value;
					this.SendPropertyChanged("MaNhanVien");
					this.OnMaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhachHang", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MaKhachHang
		{
			get
			{
				return this._MaKhachHang;
			}
			set
			{
				if ((this._MaKhachHang != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhachHangChanging(value);
					this.SendPropertyChanging();
					this._MaKhachHang = value;
					this.SendPropertyChanged("MaKhachHang");
					this.OnMaKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLichChay_Xe", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MaLichChay_Xe
		{
			get
			{
				return this._MaLichChay_Xe;
			}
			set
			{
				if ((this._MaLichChay_Xe != value))
				{
					if (this._LichChay_Xe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLichChay_XeChanging(value);
					this.SendPropertyChanging();
					this._MaLichChay_Xe = value;
					this.SendPropertyChanged("MaLichChay_Xe");
					this.OnMaLichChay_XeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fl_Xoa", DbType="Int NOT NULL")]
		public int fl_Xoa
		{
			get
			{
				return this._fl_Xoa;
			}
			set
			{
				if ((this._fl_Xoa != value))
				{
					this.Onfl_XoaChanging(value);
					this.SendPropertyChanging();
					this._fl_Xoa = value;
					this.SendPropertyChanged("fl_Xoa");
					this.Onfl_XoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VeXe_ChiTietVeXe", Storage="_ChiTietVeXes", ThisKey="MaVeXe", OtherKey="MaVeXe")]
		public EntitySet<ChiTietVeXe> ChiTietVeXes
		{
			get
			{
				return this._ChiTietVeXes;
			}
			set
			{
				this._ChiTietVeXes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_VeXe", Storage="_KhachHang", ThisKey="MaKhachHang", OtherKey="MaKhachHang", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.VeXes.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.VeXes.Add(this);
						this._MaKhachHang = value.MaKhachHang;
					}
					else
					{
						this._MaKhachHang = default(string);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LichChay_Xe_VeXe", Storage="_LichChay_Xe", ThisKey="MaLichChay_Xe", OtherKey="MaLichChay_Xe", IsForeignKey=true)]
		public LichChay_Xe LichChay_Xe
		{
			get
			{
				return this._LichChay_Xe.Entity;
			}
			set
			{
				LichChay_Xe previousValue = this._LichChay_Xe.Entity;
				if (((previousValue != value) 
							|| (this._LichChay_Xe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LichChay_Xe.Entity = null;
						previousValue.VeXes.Remove(this);
					}
					this._LichChay_Xe.Entity = value;
					if ((value != null))
					{
						value.VeXes.Add(this);
						this._MaLichChay_Xe = value.MaLichChay_Xe;
					}
					else
					{
						this._MaLichChay_Xe = default(string);
					}
					this.SendPropertyChanged("LichChay_Xe");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_VeXe", Storage="_NhanVien", ThisKey="MaNhanVien", OtherKey="MaNhanVien", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.VeXes.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.VeXes.Add(this);
						this._MaNhanVien = value.MaNhanVien;
					}
					else
					{
						this._MaNhanVien = default(string);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietVeXes(ChiTietVeXe entity)
		{
			this.SendPropertyChanging();
			entity.VeXe = this;
		}
		
		private void detach_ChiTietVeXes(ChiTietVeXe entity)
		{
			this.SendPropertyChanging();
			entity.VeXe = null;
		}
	}
}
#pragma warning restore 1591
