//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopMyPham.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QL_MyPhamEntities3 : DbContext
    {
        public QL_MyPhamEntities3()
            : base("name=QL_MyPhamEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTietDonHang> ChiTietDonHang { get; set; }
        public virtual DbSet<ChiTietNhapHang> ChiTietNhapHang { get; set; }
        public virtual DbSet<DonHang> DonHang { get; set; }
        public virtual DbSet<LoaiSanPham> LoaiSanPham { get; set; }
        public virtual DbSet<NhaCungCap> NhaCungCap { get; set; }
        public virtual DbSet<NhapHang> NhapHang { get; set; }
        public virtual DbSet<SanPham> SanPham { get; set; }
        public virtual DbSet<ThongTin> ThongTin { get; set; }
    
        public virtual int SuaChiTietDonHang(Nullable<int> maDonHang, Nullable<int> maSP, Nullable<int> soLuong)
        {
            var maDonHangParameter = maDonHang.HasValue ?
                new ObjectParameter("MaDonHang", maDonHang) :
                new ObjectParameter("MaDonHang", typeof(int));
    
            var maSPParameter = maSP.HasValue ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(int));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SuaChiTietDonHang", maDonHangParameter, maSPParameter, soLuongParameter);
        }
    
        public virtual int SuaDonHang(Nullable<int> maDonHang, Nullable<System.DateTime> ngayDat, Nullable<int> daThanhToan, Nullable<int> tinhTrangGiaoHang, Nullable<int> maKH)
        {
            var maDonHangParameter = maDonHang.HasValue ?
                new ObjectParameter("MaDonHang", maDonHang) :
                new ObjectParameter("MaDonHang", typeof(int));
    
            var ngayDatParameter = ngayDat.HasValue ?
                new ObjectParameter("NgayDat", ngayDat) :
                new ObjectParameter("NgayDat", typeof(System.DateTime));
    
            var daThanhToanParameter = daThanhToan.HasValue ?
                new ObjectParameter("DaThanhToan", daThanhToan) :
                new ObjectParameter("DaThanhToan", typeof(int));
    
            var tinhTrangGiaoHangParameter = tinhTrangGiaoHang.HasValue ?
                new ObjectParameter("TinhTrangGiaoHang", tinhTrangGiaoHang) :
                new ObjectParameter("TinhTrangGiaoHang", typeof(int));
    
            var maKHParameter = maKH.HasValue ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SuaDonHang", maDonHangParameter, ngayDatParameter, daThanhToanParameter, tinhTrangGiaoHangParameter, maKHParameter);
        }
    
        public virtual int SuaKH(Nullable<int> ma, string hoTen, string gioTinh, string diaChi, string dienThoai, string email, string taiKhoan, string matKhau)
        {
            var maParameter = ma.HasValue ?
                new ObjectParameter("Ma", ma) :
                new ObjectParameter("Ma", typeof(int));
    
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var gioTinhParameter = gioTinh != null ?
                new ObjectParameter("GioTinh", gioTinh) :
                new ObjectParameter("GioTinh", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var dienThoaiParameter = dienThoai != null ?
                new ObjectParameter("DienThoai", dienThoai) :
                new ObjectParameter("DienThoai", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var taiKhoanParameter = taiKhoan != null ?
                new ObjectParameter("TaiKhoan", taiKhoan) :
                new ObjectParameter("TaiKhoan", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SuaKH", maParameter, hoTenParameter, gioTinhParameter, diaChiParameter, dienThoaiParameter, emailParameter, taiKhoanParameter, matKhauParameter);
        }
    
        public virtual int SuaLoaiSanPham(Nullable<int> maLoaiSP, string tenLoaiSanPham)
        {
            var maLoaiSPParameter = maLoaiSP.HasValue ?
                new ObjectParameter("MaLoaiSP", maLoaiSP) :
                new ObjectParameter("MaLoaiSP", typeof(int));
    
            var tenLoaiSanPhamParameter = tenLoaiSanPham != null ?
                new ObjectParameter("TenLoaiSanPham", tenLoaiSanPham) :
                new ObjectParameter("TenLoaiSanPham", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SuaLoaiSanPham", maLoaiSPParameter, tenLoaiSanPhamParameter);
        }
    
        public virtual int SuaNhaCungCap(Nullable<int> maNCC, string tenNCC, string diaChi, string dienThoai)
        {
            var maNCCParameter = maNCC.HasValue ?
                new ObjectParameter("MaNCC", maNCC) :
                new ObjectParameter("MaNCC", typeof(int));
    
            var tenNCCParameter = tenNCC != null ?
                new ObjectParameter("TenNCC", tenNCC) :
                new ObjectParameter("TenNCC", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var dienThoaiParameter = dienThoai != null ?
                new ObjectParameter("DienThoai", dienThoai) :
                new ObjectParameter("DienThoai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SuaNhaCungCap", maNCCParameter, tenNCCParameter, diaChiParameter, dienThoaiParameter);
        }
    
        public virtual int SuaNV(Nullable<int> ma, string hoTen, string gioTinh, string diaChi, string dienThoai, string email, string taiKhoan, string matKhau)
        {
            var maParameter = ma.HasValue ?
                new ObjectParameter("Ma", ma) :
                new ObjectParameter("Ma", typeof(int));
    
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var gioTinhParameter = gioTinh != null ?
                new ObjectParameter("GioTinh", gioTinh) :
                new ObjectParameter("GioTinh", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var dienThoaiParameter = dienThoai != null ?
                new ObjectParameter("DienThoai", dienThoai) :
                new ObjectParameter("DienThoai", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var taiKhoanParameter = taiKhoan != null ?
                new ObjectParameter("TaiKhoan", taiKhoan) :
                new ObjectParameter("TaiKhoan", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SuaNV", maParameter, hoTenParameter, gioTinhParameter, diaChiParameter, dienThoaiParameter, emailParameter, taiKhoanParameter, matKhauParameter);
        }
    
        public virtual int SuaSanPham(Nullable<int> maSP, string tenSP, Nullable<int> giaBan, string moTa, string anhBia, Nullable<int> soLuongTon, Nullable<int> maNCC, Nullable<int> maLoaiSP)
        {
            var maSPParameter = maSP.HasValue ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(int));
    
            var tenSPParameter = tenSP != null ?
                new ObjectParameter("TenSP", tenSP) :
                new ObjectParameter("TenSP", typeof(string));
    
            var giaBanParameter = giaBan.HasValue ?
                new ObjectParameter("GiaBan", giaBan) :
                new ObjectParameter("GiaBan", typeof(int));
    
            var moTaParameter = moTa != null ?
                new ObjectParameter("MoTa", moTa) :
                new ObjectParameter("MoTa", typeof(string));
    
            var anhBiaParameter = anhBia != null ?
                new ObjectParameter("AnhBia", anhBia) :
                new ObjectParameter("AnhBia", typeof(string));
    
            var soLuongTonParameter = soLuongTon.HasValue ?
                new ObjectParameter("SoLuongTon", soLuongTon) :
                new ObjectParameter("SoLuongTon", typeof(int));
    
            var maNCCParameter = maNCC.HasValue ?
                new ObjectParameter("MaNCC", maNCC) :
                new ObjectParameter("MaNCC", typeof(int));
    
            var maLoaiSPParameter = maLoaiSP.HasValue ?
                new ObjectParameter("MaLoaiSP", maLoaiSP) :
                new ObjectParameter("MaLoaiSP", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SuaSanPham", maSPParameter, tenSPParameter, giaBanParameter, moTaParameter, anhBiaParameter, soLuongTonParameter, maNCCParameter, maLoaiSPParameter);
        }
    
        public virtual int ThemChiTietDonHang(Nullable<int> maDonHang, Nullable<int> maSP, Nullable<int> soLuong, Nullable<int> donGia)
        {
            var maDonHangParameter = maDonHang.HasValue ?
                new ObjectParameter("MaDonHang", maDonHang) :
                new ObjectParameter("MaDonHang", typeof(int));
    
            var maSPParameter = maSP.HasValue ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(int));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            var donGiaParameter = donGia.HasValue ?
                new ObjectParameter("DonGia", donGia) :
                new ObjectParameter("DonGia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemChiTietDonHang", maDonHangParameter, maSPParameter, soLuongParameter, donGiaParameter);
        }
    
        public virtual int ThemChiTietNhapHang(Nullable<int> maNhapHang, Nullable<int> maSP, Nullable<int> soLuong, Nullable<int> donGia)
        {
            var maNhapHangParameter = maNhapHang.HasValue ?
                new ObjectParameter("MaNhapHang", maNhapHang) :
                new ObjectParameter("MaNhapHang", typeof(int));
    
            var maSPParameter = maSP.HasValue ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(int));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            var donGiaParameter = donGia.HasValue ?
                new ObjectParameter("DonGia", donGia) :
                new ObjectParameter("DonGia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemChiTietNhapHang", maNhapHangParameter, maSPParameter, soLuongParameter, donGiaParameter);
        }
    
        public virtual int ThemDonHang(Nullable<System.DateTime> ngayDat, Nullable<int> maKH)
        {
            var ngayDatParameter = ngayDat.HasValue ?
                new ObjectParameter("NgayDat", ngayDat) :
                new ObjectParameter("NgayDat", typeof(System.DateTime));
    
            var maKHParameter = maKH.HasValue ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemDonHang", ngayDatParameter, maKHParameter);
        }
    
        public virtual int ThemLoaiSanPham(string tenLoaiSanPham)
        {
            var tenLoaiSanPhamParameter = tenLoaiSanPham != null ?
                new ObjectParameter("TenLoaiSanPham", tenLoaiSanPham) :
                new ObjectParameter("TenLoaiSanPham", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemLoaiSanPham", tenLoaiSanPhamParameter);
        }
    
        public virtual int ThemNhaCungCap(string tenNCC, string diaChi, string dienThoai)
        {
            var tenNCCParameter = tenNCC != null ?
                new ObjectParameter("TenNCC", tenNCC) :
                new ObjectParameter("TenNCC", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var dienThoaiParameter = dienThoai != null ?
                new ObjectParameter("DienThoai", dienThoai) :
                new ObjectParameter("DienThoai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemNhaCungCap", tenNCCParameter, diaChiParameter, dienThoaiParameter);
        }
    
        public virtual int ThemNhapHang(Nullable<System.DateTime> ngayNhap, Nullable<int> maNCC, Nullable<int> maNV)
        {
            var ngayNhapParameter = ngayNhap.HasValue ?
                new ObjectParameter("NgayNhap", ngayNhap) :
                new ObjectParameter("NgayNhap", typeof(System.DateTime));
    
            var maNCCParameter = maNCC.HasValue ?
                new ObjectParameter("MaNCC", maNCC) :
                new ObjectParameter("MaNCC", typeof(int));
    
            var maNVParameter = maNV.HasValue ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemNhapHang", ngayNhapParameter, maNCCParameter, maNVParameter);
        }
    
        public virtual int ThemNV(string hoTen, string gioTinh, string diaChi, string dienThoai, string email, string taiKhoan, string matKhau)
        {
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var gioTinhParameter = gioTinh != null ?
                new ObjectParameter("GioTinh", gioTinh) :
                new ObjectParameter("GioTinh", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var dienThoaiParameter = dienThoai != null ?
                new ObjectParameter("DienThoai", dienThoai) :
                new ObjectParameter("DienThoai", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var taiKhoanParameter = taiKhoan != null ?
                new ObjectParameter("TaiKhoan", taiKhoan) :
                new ObjectParameter("TaiKhoan", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemNV", hoTenParameter, gioTinhParameter, diaChiParameter, dienThoaiParameter, emailParameter, taiKhoanParameter, matKhauParameter);
        }
    
        public virtual int ThemSanPham(string tenSP, Nullable<int> giaBan, string moTa, string anhBia, Nullable<int> soLuongTon, Nullable<int> maNCC, Nullable<int> maLoaiSP)
        {
            var tenSPParameter = tenSP != null ?
                new ObjectParameter("TenSP", tenSP) :
                new ObjectParameter("TenSP", typeof(string));
    
            var giaBanParameter = giaBan.HasValue ?
                new ObjectParameter("GiaBan", giaBan) :
                new ObjectParameter("GiaBan", typeof(int));
    
            var moTaParameter = moTa != null ?
                new ObjectParameter("MoTa", moTa) :
                new ObjectParameter("MoTa", typeof(string));
    
            var anhBiaParameter = anhBia != null ?
                new ObjectParameter("AnhBia", anhBia) :
                new ObjectParameter("AnhBia", typeof(string));
    
            var soLuongTonParameter = soLuongTon.HasValue ?
                new ObjectParameter("SoLuongTon", soLuongTon) :
                new ObjectParameter("SoLuongTon", typeof(int));
    
            var maNCCParameter = maNCC.HasValue ?
                new ObjectParameter("MaNCC", maNCC) :
                new ObjectParameter("MaNCC", typeof(int));
    
            var maLoaiSPParameter = maLoaiSP.HasValue ?
                new ObjectParameter("MaLoaiSP", maLoaiSP) :
                new ObjectParameter("MaLoaiSP", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemSanPham", tenSPParameter, giaBanParameter, moTaParameter, anhBiaParameter, soLuongTonParameter, maNCCParameter, maLoaiSPParameter);
        }
    
        public virtual int UpdateDHDaGiaoHang(Nullable<int> maDonHang)
        {
            var maDonHangParameter = maDonHang.HasValue ?
                new ObjectParameter("MaDonHang", maDonHang) :
                new ObjectParameter("MaDonHang", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateDHDaGiaoHang", maDonHangParameter);
        }
    
        public virtual int UpdateDHDaThanhToan(Nullable<int> maDonHang)
        {
            var maDonHangParameter = maDonHang.HasValue ?
                new ObjectParameter("MaDonHang", maDonHang) :
                new ObjectParameter("MaDonHang", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateDHDaThanhToan", maDonHangParameter);
        }
    
        public virtual int XoaAllChiTietSanPham(Nullable<int> maDonHang)
        {
            var maDonHangParameter = maDonHang.HasValue ?
                new ObjectParameter("MaDonHang", maDonHang) :
                new ObjectParameter("MaDonHang", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaAllChiTietSanPham", maDonHangParameter);
        }
    
        public virtual int XoaChiTietSanPham(Nullable<int> maDonHang, Nullable<int> maSP)
        {
            var maDonHangParameter = maDonHang.HasValue ?
                new ObjectParameter("MaDonHang", maDonHang) :
                new ObjectParameter("MaDonHang", typeof(int));
    
            var maSPParameter = maSP.HasValue ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaChiTietSanPham", maDonHangParameter, maSPParameter);
        }
    
        public virtual int XoaDonHang(Nullable<int> maDonHang)
        {
            var maDonHangParameter = maDonHang.HasValue ?
                new ObjectParameter("MaDonHang", maDonHang) :
                new ObjectParameter("MaDonHang", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaDonHang", maDonHangParameter);
        }
    
        public virtual int XoaKH(Nullable<int> ma)
        {
            var maParameter = ma.HasValue ?
                new ObjectParameter("Ma", ma) :
                new ObjectParameter("Ma", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaKH", maParameter);
        }
    
        public virtual int XoaLoaiSanPham(Nullable<int> maLoaiSP)
        {
            var maLoaiSPParameter = maLoaiSP.HasValue ?
                new ObjectParameter("MaLoaiSP", maLoaiSP) :
                new ObjectParameter("MaLoaiSP", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaLoaiSanPham", maLoaiSPParameter);
        }
    
        public virtual int XoaNhaCungCap(Nullable<int> maNCC)
        {
            var maNCCParameter = maNCC.HasValue ?
                new ObjectParameter("MaNCC", maNCC) :
                new ObjectParameter("MaNCC", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaNhaCungCap", maNCCParameter);
        }
    
        public virtual int XoaNV(Nullable<int> ma)
        {
            var maParameter = ma.HasValue ?
                new ObjectParameter("Ma", ma) :
                new ObjectParameter("Ma", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaNV", maParameter);
        }
    
        public virtual int XoaSanPham(Nullable<int> maSP)
        {
            var maSPParameter = maSP.HasValue ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaSanPham", maSPParameter);
        }
    }
}
